config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root :to => "categories#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "splash#index", as: :unauthenticated_root
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories_expenses
  resources :expenses 
  resources :categories
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, Category, user: user if user.present?
    can :manage, Expense, author: user if user.present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_expense.rb
class CategoriesExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense

  validates :category_id, presence: true
  validates :expense_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_expenses
  has_many :expenses, through: :categories_expenses
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true

  def compute_total_expenses(expenses)
    expenses.map(&:amount).sum
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categories_expenses
  has_many :categories, through: :categories_expenses

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy, foreign_key: 'author_id'

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @categories = current_user.categories.order(created_at: :desc).all
    @total_expenses = []

    @categories.each do |category|
      total = 0
      category.categories_expenses.each do |category_expense|
        total += category_expense.expense.amount
      end
      @total_expenses.push(total)
    end
  end

  def show
    @expenses = @category.expenses.order(created_at: :desc)
    @category_id = Category.find(@expenses[0].category_id) unless @expenses.empty?
    @total_expenses = @category.compute_total_expenses(@expenses)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      format.html do
        if @category.save
          flash[:notice] = 'Category added successfully.'
          redirect_to categories_path
        else
          flash[:alert] = 'Category creation failed. Try again'
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # before_action :authenticate_user!
  load_and_authorize_resource

  def show
    @expense = Expense.find(params[:id])
    @category_id = Category.find(@expense.category_id)
  end

  def new
    @expense = Expense.new
    @categories = Category.all
  end

  def create
    @new_expense = current_user.expenses.new(expense_params)
    @categories = Category.all

    respond_to do |format|
      format.html do
        if @new_expense.save
          CategoriesExpense.create(category_id: @new_expense.category_id, expense_id: @new_expense.id)
          flash[:notice] = 'Transaction added successfully.'
          redirect_to category_path(@new_expense.category_id)
        else
          flash[:alert] = 'Transaction creation failed. Try again'
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category_list.html.erb
            <li class="py-3 sm:py-4">
                <div class="flex items-center space-x-4">
                    <div class="flex-shrink-0">
                        <img class="w-8 h-8 rounded-full" src="<%= category.icon %>" alt="Category Icon">
                    </div>
                    <div class="flex-1 min-w-0">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            <%= category.name %>
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                        <%= category.created_at %>
                        </p>
                    </div>
                    
        

app/views/categories/index.html.erb
<div class="p-4 w-xl bg-white border shadow-lg sm:p-8 dark:bg-gray-800 dark:border-gray-700">
<div class="flex justify-between items-center mb-10">
    <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">All Expense Categories</h5>
    <%= link_to "Back", categories_path, class:"bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-full" %>
</div>
<% if @categories.empty? %>
    <p class="text-xl font-bold leading-none text-gray-900 dark:text-white mb-5">Hello! No categories found. Please add one</p>
    <%= link_to "Add Category", new_category_path, 
    class:"md:w-full bg-blue-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-blue-500 hover:border-blue-100 rounded-full" %>
<div class="flow-root">
    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700 mb-5 list-none">
    <% else %>
      <% @categories.each_with_index  do |c, index| %>
        <%= link_to category_path(c.id), style:"text-decoration: none; color: black" do %>
        <%= render 'category_list', :category => c %>
        <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                    <% if  !@total_expenses.empty? %>
                    $<%= @total_expenses[index] %>
                    <% else %>
                    0
                    <% end %>
                    </div>
                </div>
            </li>
        <% end %>
      <% end %>
      <li class="py-5 w-full">
          <div class="flex items-center space-x-4 w-full">
          <%= link_to "Add Category", new_category_path, 
      class:"text-center w-full bg-blue-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-blue-500 hover:border-blue-100 rounded-full ml-30" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_with model: @category do |f| %>  
<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
<div class="-mx-3 md:flex mb-6">
<div class="md:w-full px-3">
<%= f.label :name, "Budget Category*", 
class:"uppercase tracking-wide text-black text-xs font-bold mb-2" %>
  <%= f.text_field :name,
  class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", id:"application-link",
   placeholder:"Please enter category eg. lunch" %>
</div>
</div>
  <div class="-mx-3 md:flex mb-6">
    <div class="md:w-full px-3">
    <%= f.label :icon, "Budget Icon*", 
      class:"uppercase tracking-wide text-black text-xs font-bold mb-2" %>
    <%= f.text_field :icon,
      class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", id:"application-link",
      placeholder:"http://...." %>
    <div>
      <span class="text-red-500 text-xs italic">
        Please fill out this field.
      </span>
    </div>
    </div>
  </div>
  <div class="-mx-3 md:flex mt-2">
    <div class="md:w-full px-3">
    <%= f.submit "Add Category", 
    class:"md:w-full bg-gray-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded-full" %>
    </div>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<div class="p-4 w-xl bg-white border shadow-lg sm:p-8 dark:bg-gray-800 dark:border-gray-700">
<div class="flex justify-between items-center mb-10">
    <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Latest Transactions</h5>
    <h5 class="text-sm font-medium text-blue-600 hover:underline dark:text-blue-500">
    Total Expenses: $<%= @total_expenses %>
    </h5>
    <%= link_to "Back", categories_path, class:"bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-full" %>
</div>
<% if @expenses.empty? %>
    <p class="text-xl font-bold leading-none text-gray-900 dark:text-white mb-5">Hello! No Transactions found. Please add one</p>
    <%= link_to "Add Transaction", new_expense_path, 
    class:"md:w-full bg-blue-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-blue-500 hover:border-blue-100 rounded-full" %>
<div class="flow-root">
    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700 mb-5 list-none">
    <% else %>
      <% @expenses.each do |e| %>
        <%= link_to expense_path(e.id), style:"text-decoration: none; color: black" do %>
        <li class="py-3 sm:py-4 mb-5">
        <div class="flex items-center space-x-4">
            <div class="flex-shrink-0">
                <img class="w-8 h-8 rounded-full" src="<%= @category_id.icon %> " alt="Category Icon">
            </div>
            <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                    <%= e.name %>
                </p>
                <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                <%= e.created_at %>
                </p>
            </div>
            <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
            $<%= e.amount %>
            </div>
        </div>
    </li>
    <% end %>
    <% end %>
    <li class="py-5 w-full">
          <div class="flex items-center space-x-4 w-full">
          <%= link_to "Add Transaction", new_expense_path, 
      class:"text-center w-full bg-blue-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-blue-500 hover:border-blue-100 rounded-full ml-30" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/expenses/_add_new_category_item.html.erb
<%= form_with url: category_items_path, method: :get  do |f| %>
  <div class="-mx-3 md:flex mb-6">
    <div class="md:w-full px-3">
      <%= f.select :category_id, @categories.collect { |category| [category.name, category.id] }, :prompt => 'Select a category',
      class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", required: true %>
      </div>
    </div>
    <div class="-mx-3 md:flex mt-2">
    <div class="md:w-full px-3">
      <%= f.submit "Add Category", 
      class:"md:w-full bg-gray-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded-full" %>
    </div>
  </div>
<% end %>

app/views/expenses/new.html.erb
<%= form_with model: @expense, url: expenses_path do |f| %>  
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
  <div class="-mx-3 md:flex mb-6">
  <div class="md:w-full px-3">
  <%= f.label :name, "Transaction*", 
  class:"uppercase tracking-wide text-black text-xs font-bold mb-2" %>
    <%= f.text_field :name,
    class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", id:"application-link",
     placeholder:"Please enter category eg. lunch" %>
  </div>
  </div>
    <div class="-mx-3 md:flex mb-6">
      <div class="md:w-full px-3">
      <%= f.label :amount, "Amount*", 
        class:"uppercase tracking-wide text-black text-xs font-bold mb-2" %>
      <%= f.number_field  :amount,
        class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", id:"application-link",
        placeholder:"Enter amount in $" %>
      <div>
        <span class="text-red-500 text-xs italic">
          Please fill out this field.
        </span>
      </div>
      </div>
    </div>
  
      <div class="-mx-3 md:flex mb-6">
        <div class="md:w-full px-3">
          <%= f.select :category_id, @categories.collect { |category| [category.name, category.id] }, :prompt => 'Select a category',
          class:"w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3", required: true %>
          </div>
        </div>
    <div class="-mx-3 md:flex mt-2">
      <div class="md:w-full px-3">
      <%= f.submit "Add Category", 
      class:"md:w-full bg-gray-900 cursor-pointer text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded-full" %>
      </div>
    </div>
  </div>
  <% end %>

app/views/expenses/show.html.erb
<div class="p-4 w-xl bg-white border shadow-lg sm:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class="flex justify-between items-center mb-10">
    <div class="flex-shrink-0">
      <img class="w-20 h-20 rounded-full" src="<%= @category_id.icon %> " alt="Category Icon">
    </div>
    <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white"><%= @expense.name %></h5>
    <%= link_to "Back", categories_path, class:"bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-full" %>
</div>
<div class="flow-root">
    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700 mb-5 list-none">
        <li class="py-3 sm:py-4 mb-5">
        <div class="flex items-center space-x-4">
            <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900 truncate dark:text-white p-10">
                   The transaction <%= @expense.name %> was added on <%= @expense.created_at %> <br> and it involved spending $<%= @expense.amount %>
                </p>
                <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                Total Amount spent on Transaction: <span class="text-xl font-bold leading-none text-gray-900 dark:text-white"> 
                <%= @expense.amount %> dollars</span>
                </p>
            </div>
        </div>
    </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Hippo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-white border shadow-lg sm:p-8 dark:bg-gray-800 dark:border-gray-700 list-none">
  <header class="bg-gray-900">
    <%= render 'shared/header' %>
  </header>
  <% if flash.any? %>
    <% flash.each do |type, msg| %>
      <% if type == 'alert' %>
        <div class="flex bg-red-100 rounded-lg p-4 mb-4">
          <svg class="w-5 h-5 text-red-700" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <p class="ml-3 text-sm text-red-700">
            <span class="font-medium">Important Note!</span> <%= msg %>
          </p>
        </div>
      <% else %>
        <div class="flex bg-blue-100 rounded-lg p-4 mb-4">
          <svg class="w-5 h-5 text-blue-700" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <p class="ml-3 text-sm text-blue-700">
            <span class="font-medium">Important Note!</span> <%= msg %>
          </p>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <main>
      <%= yield %>
  </main>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
  <%= link_to categories_path, class:"flex items-center" do %>
      <img src="https://image.shutterstock.com/image-photo/saving-money-hippo-bank-conceptbusiness-600w-593646404.jpg" 
      class="mr-3 h-6 sm:h-9 rounded-full" alt="Flowbite Logo" />
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Budget Hippo</span>
    <% end  %>
  <div class="flex items-center">
  <% if user_signed_in? %>
  <ul class="flex flex-row navbar-nav me-auto pt-0">
    <li class="nav-item mr-5">
    <h6 class= "text-white">Welcome,  <%= current_user.name %></h6>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign Out', destroy_user_session_path , method: :delete, class: "text-sm font-semibold whitespace-nowrap dark:text-white" %>
  </li>
  <% else %>
        <ul class="flex flex-row navbar-nav ml-auto">
        <li class="nav-item mr-4">
          <%= link_to 'Sign Up', new_user_registration_path , class: "text-sm font-semibold whitespace-nowrap dark:text-white" %>
        </li>
        <li class="nav-item mr-4">
          <%= link_to 'Sign In', new_user_session_path , class: "text-sm font-semibold whitespace-nowrap dark:text-white" %>
        </li>
      </ul>
  <% end %>
</ul>
      </div>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="w-full bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
    <div class="flex flex-col items-center pb-10">
        <img class="mb-3 mt-6 w-40 h-40 rounded-full shadow-lg" 
        src="https://thumbs.dreamstime.com/b/rich-joyful-hippo-money-hippopotamus-rejoices-emerging-them-joy-making-income-profit-emotion-received-202987357.jpg" alt="Bonnie image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Budget Hippo</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">The ultimate app to help you manage your finances</span>
        <div class="flex mt-10 space-x-3 lg:mt-6">
            <%= link_to "Sign up", new_user_registration_path, 
            class: "inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <%= link_to "Log in", new_user_session_path , class:"inline-flex items-center py-2 px-4 text-sm font-medium text-center text-gray-900 bg-white rounded-lg border border-gray-300 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700" %>
        </div>
    </div>
</div>